
# Site settings
name: "Pho Hack's Sake"
title: null
description: A noodly ride on my journey into software development, info security, linux systems, and pwning
baseurl: /noodulz.github.io
url: https://www.noodulz.github.io

# Social Media and Contact Info
twitter_username: nooduulz
github_username:  noodulz
email: jocelyndzuong@ufl.edu 

# Build settings
timezone: America/New_York
markdown: kramdown
remote_theme: mattvh/solar-theme-jekyll
plugins:
  - jekyll-feed
gems: [jekyll-paginate]
plugins: [jekyll-paginate]
permalink: /:year/:month/:day/:title/
paginate: 10
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
